# Generated by Django 3.0.5 on 2020-04-26 05:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0002_recipepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 26, 5, 29, 4, 395917, tzinfo=utc)),
        ),
    ]
