# Generated by Django 3.0.5 on 2020-05-02 08:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0003_auto_20200426_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipepost',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 8, 53, 21, 304895, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
