# Generated by Django 3.0.5 on 2020-05-02 09:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0004_auto_20200502_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 9, 9, 53, 891800, tzinfo=utc)),
        ),
    ]
