# Generated by Django 3.0.5 on 2020-05-02 09:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0005_auto_20200502_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 2, 9, 16, 27, 898508, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='image',
            field=models.ImageField(blank=True, upload_to='recipe_images'),
        ),
    ]
