# Generated by Django 3.0.5 on 2020-05-05 04:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0007_auto_20200504_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 5, 4, 36, 28, 475602, tzinfo=utc)),
        ),
    ]
