# Generated by Django 3.0.5 on 2020-05-09 05:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0008_auto_20200505_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipepost',
            old_name='text',
            new_name='description',
        ),
        migrations.AddField(
            model_name='recipepost',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recipepost',
            name='recipe',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 5, 3, 33, 322127, tzinfo=utc)),
        ),
    ]
