# Generated by Django 3.0.5 on 2020-05-09 06:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0012_auto_20200509_1515'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipepost',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 6, 21, 30, 883532, tzinfo=utc)),
        ),
    ]
