# Generated by Django 3.0.5 on 2020-05-09 09:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0013_auto_20200509_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 9, 9, 20, 11, 290358, tzinfo=utc)),
        ),
    ]
