# Generated by Django 3.0.5 on 2020-06-21 05:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0015_auto_20200621_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 21, 5, 13, 45, 746112, tzinfo=utc)),
        ),
    ]
