# Generated by Django 3.0.5 on 2020-12-11 00:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0017_auto_20200629_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 0, 3, 4, 709918, tzinfo=utc)),
        ),
    ]
