# Generated by Django 3.0.5 on 2020-12-11 00:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0018_auto_20201211_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 11, 0, 4, 23, 741529, tzinfo=utc)),
        ),
    ]
