# Generated by Django 3.0.5 on 2020-12-15 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_app', '0020_auto_20201211_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipepost',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 15, 11, 43, 42, 112571, tzinfo=utc)),
        ),
    ]
